name: Release Check

on: 
  push:
    branches:
      - 'release-**'
  pull_request:
    branches: 
      - 'release-**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout Branch
      uses: actions/checkout@v3
      with:
        path: branch
              
    - name: Checkout Master
      uses: actions/checkout@v3
      with:
        ref: 'master'
        path: master
        
    - name: Get version from Master
      id: versionReader0
      uses: Devofure/version-reader-action@v1.0.0
      with:
        gradlePath: master/app/build.gradle          
        
    - name: Get version from Branch
      id: versionReader1
      uses: Devofure/version-reader-action@v1.0.0
      with:
        gradlePath: branch/app/build.gradle
        
    - name: Verify bump versionCode
      uses: jackbilestech/semver-compare@b6b063c569b77bea4a0ab627192cbdabf75de3f5
      with:
        head: '0.${{ steps.versionReader1.outputs.versionCode }}.0'
        base: '0.${{ steps.versionReader0.outputs.versionCode }}.0'
        operator: '>'

    - name: Verify bump versionName
      uses: jackbilestech/semver-compare@b6b063c569b77bea4a0ab627192cbdabf75de3f5
      with:
        head: '${{ steps.versionReader1.outputs.versionName }}'
        base: '${{ steps.versionReader0.outputs.versionName }}'
        operator: '>'
